### ISSUE TITLE
Breast Cancer Prediction Model using ML Models

### ISSUE THREAD

**Issue by jainriya9** [Soumya-Kushwaha/ML-Fest#11]
In this Prediction model, Machine Learning models like Decision Tree Classifier will be used to predict the chances of encountering Breast Cancer in patients after analysing several attributes. Visual representation of the relationships between attributes and Heatmap will be generated to anaylze better. 

Thankyou!

**Comment by Soumya-Kushwaha** [comment]
Looking forward @jainriya9!

**Comment by jainriya9** [comment]
> Looking forward @jainriya9!

Thankyou!

**Comment by jainriya9** [comment]
I have made the Pull Request.
Thankyou!
@Soumya-Kushwaha

**Comment by Soumya-Kushwaha** [comment]
@jainriya9 I had to revert your PR. It changed the complete repo's README & files were all distributed everywhere. 
If you want to make a PR, please create a separate folder called "Breast Cancer Prediction" & put all files including README in it.
I'd suggest creating a new branch in your fork, creating new folder, adding all necessary files & then finally submitting a pull request.
You might want to fork again, due to compatibility issues. Just make sure to sync your fork, before working.

Hope it helps.
Happy Hacktoberfest :)

**Comment by jainriya9** [comment]
> @jainriya9 I had to revert your PR. It changed the complete repo's README & files were all distributed everywhere. If you want to make a PR, please create a separate folder called "Breast Cancer Prediction" & put all files including README in it. I'd suggest creating a new branch in your fork, creating new folder, adding all necessary files & then finally submitting a pull request. You might want to fork again, due to compatibility issues. Just make sure to sync your fork, before working.
> 
> Hope it helps. Happy Hacktoberfest :)

Sure I'll add in the required format.
